### PR TITLE
Hammxah OOSE assignment

### PR DESCRIPTION
**Pull request by hammxah**

### CODE REVIEW

**Comment by ahsannabi** [comment]
1. Please fully qualify the name of your first assignment document like this:
RequirementElicitationDocument-GroupMemberName.docx or the name of the group member uploading from his GitHub account
Like RequirementElicitationDocument-Hamza-Farrukh.docx
2. Any other file you need to commit, like readme.md you rename accordingly, like:
Readme-Hamza-Furrukh, so that ahsannabi main branch does not get duplicate file confusions.
3. Please list the names of all your group members with roll numbers.
Thank you.

**Comment by hammxah** [comment]
[SoftwareRequirementSpecification-HamzaFarrukh.docx](https://github.com/ahsannabi/Object-Oriented-Software-Engineering/files/1900060/SoftwareRequirementSpecification-HamzaFarrukh.docx)

**Comment by ahsannabi** [comment]
Received

**Comment by hammxah** [comment]
[HealthCareSystem-HamzaFarrukh.zip](https://github.com/ahsannabi/Object-Oriented-Software-Engineering/files/1981653/HealthCareSystem-HamzaFarrukh.zip)

**Pull request closed without merging**
